# Generated by Django 3.2.23 on 2023-11-14 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_showreel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='contact_email',
            field=models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='video',
            name='video_download_link',
            field=models.CharField(default='', max_length=200, unique=True, validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='follow_me_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
