# Generated by Django 3.2.25 on 2025-08-14 20:01

from django.db import migrations, models
import vote.models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_add_email_and_download_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='steam_link',
            field=models.URLField(blank=True, default='', validators=[vote.models._validate_steam_store_url]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.URLField(unique=True, validators=[vote.models._validate_youtube_url]),
        ),
    ]
