# Generated by Django 3.2.25 on 2025-08-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20250814_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='steam_link',
        ),
        migrations.AddField(
            model_name='video',
            name='store_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
