"""empty message

Revision ID: 4278cd52c364
Revises: 
Create Date: 2025-09-16 17:50:32.872204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4278cd52c364'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showreels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('OPENED_TO_SUBMISSIONS', 'VOTE', 'CLOSED', name='showreelstatus'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_showreels'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=128), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('showreel_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=200), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('video_link', sa.String(length=200), nullable=False),
    sa.Column('video_download_link', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('follow_me_link', sa.String(length=200), nullable=True),
    sa.Column('store_link', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_videos_author_id_users')),
    sa.ForeignKeyConstraint(['showreel_id'], ['showreels.id'], name=op.f('fk_videos_showreel_id_showreels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos')),
    sa.UniqueConstraint('video_download_link', name=op.f('uq_videos_video_download_link')),
    sa.UniqueConstraint('video_link', name=op.f('uq_videos_video_link'))
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_votes_user_id_users')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_votes_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_votes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('videos')
    op.drop_table('users')
    op.drop_table('showreels')
    # ### end Alembic commands ###
